---
title: "Domestic_airlines.Rmd"
author: "Fabien"
date: "25/07/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE, 
                      warning = FALSE)
library(tidyverse)
```


```{r}
fn_data <- "domestic_airline_performance.csv"
fn_notes <- "domestic_airline_performance_notes.txt"

if(!file.exists(fn_data)) {
  url_data <- "https://data.gov.au/data/dataset/29128ebd-dbaa-4ff5-8b86-d9f30de56452/resource/cf663ed1-0c5e-497f-aea9-e74bfda9cf44/download/otp_time_series_web.csv"
  url_notes <- "https://data.gov.au/data/dataset/29128ebd-dbaa-4ff5-8b86-d9f30de56452/resource/69e214b9-b66f-4636-9c84-3efda2d0d8ae/download/otptimeserieswebnotes.txt"

  download.file(url_data, fn_data)
  download.file(url_notes, fn_notes)
}

df <- read_csv(fn_data, quote = "")
df
```

```{r echo = F}
d <- df %>% dim
```

Number of rows i.e. observations `r d[1]` and number columns i.e. variables `r d[2]`


### Additional information about the data set

```{r child = 'domestic_airline_performance_notes.txt'}

```

## Visualisation
```{r}
df2 <- df %>% filter((Airline == 'Jetstar' | Airline == 'Qantas'),
                     Route != 'All Ports-All Ports')
```

```{r echo = FALSE}
df2 %>%
  group_by(Airline, Year, Departing_Port) %>%
  summarise(n = n()) %>%
  ungroup %>%
    ggplot(aes(Departing_Port, n, color = Airline)) +
    geom_boxplot() +
    theme(axis.text.x=element_text(angle=45, hjust=1))
```


```{r echo = FALSE, fig.height = 4, fig.width = 4, fig.align = 'center', fig.cap = 'Figure 1. **Title** _subtitle_'}
df2 %>%
  group_by(Airline, Year, Departing_Port) %>%
  summarise(n = n()) %>%
  ungroup %>%
    ggplot(aes(Departing_Port, n, color = Airline)) +
    geom_boxplot() +
    theme(axis.text.x=element_text(angle=45, hjust=1))
```
